Repository li-sense/Back-end, pull requests merged in 2022-11, with the labels that each got.

#28 feat: Integrando API Mercado Pago e rota de pagamento por boleto bancário.
  app/routes/v1_endpoint/produto_routes.py
  app/utils/payment_by_bankSlip.py
  requirements.txt
Labels: feature

#32 Feature/s03/t126 certificado de compra
  .gitignore
  app/routes/api_config.py
  app/routes/v1_endpoint/certificate_routes.py
  app/schemas/certificado_schemas.py
  requirements.txt
Labels: feature

#33 feat: Criação das rotas, models e schemas do endereço do usuário
  app/models/__all__models.py
  app/models/endereco_models.py
  app/routes/api_config.py
  app/routes/v1_endpoint/endereco_usuario_routes.py
  app/schemas/endereco_schemas.py
Labels: feature

#30 feat: redefinição de senha usuário
  app/config/configs.py
  app/routes/v1_endpoint/usuario_routes.py
  app/schemas/usuario_mensagem_schemas.py
  app/utils/email_config.py
  requirements.txt
Labels: feature

#27 feat:finalizando implementacao adicionar imagens produtos
  app/models/__all__models.py
  app/models/image_produto_models.py
  app/routes/v1_endpoint/produto_routes.py
  app/schemas/image_product_schemas.py
  database.db
  static/images/0cbe5bd198b1f36a8776.jpg
  static/images/4077408eccfed99288b8.jpg
  static/images/b9cae28d2b2d1d388f38.jpg
Labels: feature

#31 feat: Criacao da avaliacao do ususario produto
  app/models/__all__models.py
  app/models/avaliacao_produtos_models.py
  app/models/product_models.py
  app/models/usuario_models.py
  app/models/vendedor_models.py
  app/routes/api_config.py
  app/routes/v1_endpoint/avaliacao_produtos_routes.py
  app/routes/v1_endpoint/vendedor_routes.py
  app/schemas/avaliacao_produtos_schemas.py
  app/schemas/vendedor_schemas.py
  app/utils/avaliacao_produtos.py
  database.db
  requirements.txt
Labels: feature

#36 Release S03
  .env-exemplo
  .gitignore
  README.md
  app/config/configs.py
  app/models/__all__models.py
  app/models/avaliacao_produtos_models.py
  app/models/endereco_models.py
  app/models/image_model.py
  app/models/image_produto_models.py
  app/models/product_models.py
  app/models/usuario_google_models.py
  app/models/usuario_models.py
  app/models/vendedor_models.py
  app/routes/api_config.py
  app/routes/v1_endpoint/avaliacao_produtos_routes.py
  app/routes/v1_endpoint/certificate_routes.py
  app/routes/v1_endpoint/endereco_usuario_routes.py
  app/routes/v1_endpoint/imagem_usuario_routes.py
  app/routes/v1_endpoint/produto_routes.py
  app/routes/v1_endpoint/usuario_routes.py
  app/routes/v1_endpoint/vendedor_routes.py
  app/schemas/avaliacao_produtos_schemas.py
  app/schemas/certificado_schemas.py
  app/schemas/endereco_schemas.py
  app/schemas/image_product_schemas.py
  app/schemas/image_schemas.py
  app/schemas/pessoa_schemas.py
  app/schemas/usuario_google_schemas.py
  app/schemas/usuario_mensagem_schemas.py
  app/schemas/vendedor_schemas.py
  app/utils/avaliacao_produtos.py
  app/utils/email_config.py
  app/utils/payment_by_bankSlip.py
  database.db
  main.py
  requirements.txt
  static/images/0cbe5bd198b1f36a8776.jpg
  static/images/4077408eccfed99288b8.jpg
  static/images/966bfe1045ae1f0bd8b5.jpg
  static/images/a27efa7781fd8b38710b.jpg
  static/images/b9cae28d2b2d1d388f38.jpg
Labels: release

#38 Refactor: Produto models, Schams e Routes
  app/models/__all__models.py
  app/models/image_produto_models.py
  app/models/product_models.py
  app/models/usuario_models.py
  app/models/vendedor_models.py
  app/routes/v1_endpoint/produto_routes.py
  app/routes/v1_endpoint/vendedor_routes.py
  app/schemas/product_schemas.py
  app/schemas/vendedor_schemas.py
  database.db
  requirements.txt
Labels: feature

#42 Feat: Refatoração avaliação produto
  app/models/product_models.py
  app/models/usuario_models.py
  app/routes/api_config.py
  app/routes/v1_endpoint/avaliacao_produtos_routes.py
  app/routes/v1_endpoint/historico_compras_usuario_routes.py
  app/routes/v1_endpoint/produto_routes.py
  app/routes/v1_endpoint/usuario_routes.py
  app/schemas/avaliacao_produtos_schemas.py
  app/schemas/historico_compras_usuario_schemas.py
  app/schemas/pessoa_schemas.py
  app/schemas/product_schemas.py
  app/schemas/vendedor_schemas.py
  app/utils/avaliacao_produtos.py
  database.db
  main.py
Labels: feature

#40 Feature/s03/t95 criacao rota schemas models para carinho
  -- SQLite.sql
  app/models/__all__models.py
  app/models/carrinho_models.py
  app/routes/api_config.py
  app/routes/v1_endpoint/carrinho_routes.py
  app/schemas/carrinho_schemas.py
  database.db
Labels: feature

#45 feat: Rota de pagamento por boleto c/ atualização do histórico de compras
  app/routes/api_config.py
  app/routes/v1_endpoint/pagamento_bol_routes.py
  app/utils/payment_by_bankSlip.py
Labels: feature

#44 feat: finalizar o crud da imagem do usuario e colocar em arquivos separados
  app/routes/v1_endpoint/imagem_usuario_routes.py
Labels: feature

#49 Refactor: Endereço
  Dockerfile
  app/models/__all__models.py
  app/models/endereco_models.py
  app/models/usuario_models.py
  app/routes/v1_endpoint/endereco_usuario_routes.py
  database.db
Labels: feature

#53 feat: Rota de pagamento boleto/reenvio
  app/routes/v1_endpoint/pagamento_bol_routes.py
  app/utils/payment_by_bankSlip.py
Labels: feature

#52 feat: finalizar o crud da imagem do usuario e colocar em arquivos separados
  app/routes/v1_endpoint/imagem_usuario_routes.py
Labels: feature

#39 feat:Pagamento_cartao
  app/models/__all__models.py
  app/models/pagamento_cartao_models.py
  app/models/usuario_models.py
  app/routes/api_config.py
  app/routes/v1_endpoint/pagamento_cartao_rota.py
  app/schemas/pagamento_cartao_schemas.py
  app/utils/pagamento_cartao.py
  database.db
  databese.db
Labels: feature

#59 Release 04
  .env-exemplo
  .gitignore
  Dockerfile
  app/asset/images/logoFinal.png
  app/config/configs.py
  app/models/__all__models.py
  app/models/carrinho_models.py
  app/models/endereco_models.py
  app/models/historico_compras_usuario_models.py
  app/models/image_produto_models.py
  app/models/licenca_models.py
  app/models/pagamento_cartao_models.py
  app/models/product_models.py
  app/models/repositorio_certificados.py
  app/models/usuario_models.py
  app/models/vendedor_models.py
  app/routes/api_config.py
  app/routes/v1_endpoint/avaliacao_produtos_routes.py
  app/routes/v1_endpoint/carrinho_routes.py
  app/routes/v1_endpoint/certificate_email.py
  app/routes/v1_endpoint/certificate_routes.py
  app/routes/v1_endpoint/endereco_usuario_routes.py
  app/routes/v1_endpoint/historico_compras_usuario_routes.py
  app/routes/v1_endpoint/imagem_produtos_routes.py
  app/routes/v1_endpoint/imagem_usuario_routes.py
  app/routes/v1_endpoint/licenca_routes.py
  app/routes/v1_endpoint/pagamento_bol_routes.py
  app/routes/v1_endpoint/pagamento_cartao_rota.py
  app/routes/v1_endpoint/produto_routes.py
  app/routes/v1_endpoint/usuario_routes.py
  app/routes/v1_endpoint/vendedor_routes.py
  app/schemas/avaliacao_produtos_schemas.py
  app/schemas/carrinho_schemas.py
  app/schemas/historico_compras_usuario_schemas.py
  app/schemas/image_product_schemas.py
  app/schemas/image_schemas.py
  app/schemas/licenca_schemas.py
  app/schemas/pagamento_cartao_schemas.py
  app/schemas/pessoa_schemas.py
  app/schemas/product_schemas.py
  app/schemas/repositorio_certificados_schemas.py
  app/schemas/vendedor_schemas.py
  app/utils/avaliacao_produtos.py
  app/utils/create_certification.py
  app/utils/pagamento_cartao.py
  app/utils/payment_by_bankSlip.py
  database.db
  main.py
  requirements.txt
  static/images/0cbe5bd198b1f36a8776.jpg
  static/images/3cff76a09c847b8d9ab9.jpg
  static/images/4077408eccfed99288b8.jpg
  static/images/966bfe1045ae1f0bd8b5.jpg
  static/images/a27efa7781fd8b38710b.jpg
  static/images/b9cae28d2b2d1d388f38.jpg
Labels: release

#60 Hotfix: Import UsuarioModels em Forma de Pagamento Cartão
  app/routes/v1_endpoint/pagamento_cartao_rota.py
  database.db
Labels: bug
