Repository li-sense/Back-end, pull requests merged in 2022-12, with the labels that each got.

#61 Refatorar: Recuperação de Senha
  alembic.ini
  app/config/configs.py
  app/models/product_models.py
  app/routes/v1_endpoint/usuario_routes.py
  app/schemas/usuario_mensagem_schemas.py
  app/utils/email_config.py
  app/utils/recuperacao_email_config.py
  database.db
  main.py
  migrations/README
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/d6a93cca2184_primeira_migracao.py
  requirements.txt
Labels: feature

#62 Release 4.1
  alembic.ini
  app/config/configs.py
  app/models/pagamento_cartao_models.py
  app/models/product_models.py
  app/models/usuario_models.py
  app/routes/v1_endpoint/usuario_routes.py
  app/schemas/usuario_mensagem_schemas.py
  app/utils/email_config.py
  app/utils/recuperacao_email_config.py
  database.db
  main.py
  migrations/README
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/d6a93cca2184_primeira_migracao.py
  requirements.txt
Labels: release

#63 Hotfix: Bug na Criação Produtos
  .env-exemplo
  app/models/product_models.py
  app/routes/v1_endpoint/produto_routes.py
  app/schemas/product_schemas.py
  database.db
Labels: bug

#69 Refatoracao: adicao do id no historico de compras
  app/routes/v1_endpoint/historico_compras_usuario_routes.py
  app/schemas/historico_compras_usuario_schemas.py
Labels: bug

#70 refactor: reajuste do crud da imagem do usuario
  app/routes/v1_endpoint/imagem_usuario_routes.py
Labels: enhancement

#68 Refactor: reajuste da estrutura da models e schem
  app/models/pagamento_cartao_models.py
  app/schemas/pagamento_cartao_schemas.py
Labels: enhancement

#66 correção bug id do produto
  app/routes/v1_endpoint/produto_routes.py
  app/schemas/product_schemas.py
  static/images/cd7dd65685cdff8534d3.png
Labels: feature

#65 Refactor/s05/t233 rafatoracao model licenca
  app/models/licenca_models.py
  app/models/product_models.py
  app/models/vendedor_models.py
Labels: enhancement

#72 Refatoracao: Usuarios, endereco e vendedor Schemas
  app/models/endereco_models.py
  app/routes/v1_endpoint/endereco_usuario_routes.py
  app/routes/v1_endpoint/usuario_routes.py
  app/routes/v1_endpoint/vendedor_routes.py
  app/schemas/endereco_schemas.py
  app/schemas/pessoa_schemas.py
  app/schemas/vendedor_schemas.py
Labels: bug

#74 Release 05
  app/models/endereco_models.py
  app/models/licenca_models.py
  app/models/pagamento_cartao_models.py
  app/models/product_models.py
  app/models/vendedor_models.py
  app/routes/v1_endpoint/carrinho_routes.py
  app/routes/v1_endpoint/certificate_email.py
  app/routes/v1_endpoint/endereco_usuario_routes.py
  app/routes/v1_endpoint/historico_compras_usuario_routes.py
  app/routes/v1_endpoint/imagem_produtos_routes.py
  app/routes/v1_endpoint/imagem_usuario_routes.py
  app/routes/v1_endpoint/produto_routes.py
  app/routes/v1_endpoint/usuario_routes.py
  app/routes/v1_endpoint/vendedor_routes.py
  app/schemas/endereco_schemas.py
  app/schemas/historico_compras_usuario_schemas.py
  app/schemas/pagamento_cartao_schemas.py
  app/schemas/pessoa_schemas.py
  app/schemas/product_schemas.py
  app/schemas/vendedor_schemas.py
  app/utils/create_certification.py
  app/utils/payment_by_bankSlip.py
  database.db
Labels: release

#78 Bugfix: Imagem Usuário e Produtos Config Licecas
  app/models/licenca_models.py
  app/models/product_models.py
  app/models/usuario_models.py
  app/models/vendedor_models.py
  app/routes/v1_endpoint/licenca_routes.py
  app/routes/v1_endpoint/produto_routes.py
  app/routes/v1_endpoint/usuario_routes.py
  app/schemas/licenca_schemas.py
  app/schemas/pessoa_schemas.py
  app/schemas/product_schemas.py
  database.db
  migrations/versions/8a55c3209d4b_ateracao_imagens_usario_produto.py
Labels: bug

#79 BugFix: correção bug recuperação de senha
  app/routes/v1_endpoint/usuario_routes.py
Labels: bug
